/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:42792dce-a64e-497a-9d73-6953e19e32f4",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_5tCgY1nSD",
  aws_user_pools_web_client_id: "6jtgvnap5nlg52pidl1pcga19h",
  oauth: {
    domain: "cloud9-hugoton-dev.auth.us-east-1.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "https://cloud9-nu.vercel.app/",
    redirectSignOut: "https://cloud9-nu.vercel.app/",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_appsync_graphqlEndpoint:
    "https://ebokwlybxbhfbaccv3ejr4yapm.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_appsync_apiKey: "da2-zq6pc24ghzetffq5jheng5l7sa",
};

export default awsmobile;
